### ISSUE TITLE
Sorting of Copied CE does not get updated

### ISSUE THREAD

**Issue by Inovanet** [DMKEBUSINESSGMBH/typo3-mkcontentai#12]
When copying content and moving to another page and inserting it to a specific position, the element is set to the top of the page instead. Looking into the database the sorting of the copied elemet is the same as the original.

Deactivating your plugin, copy and insert to a specific position works fine and as intended.

**Comment by hannesbochmann** [comment]
Thanks for the report. We will have a look at the problem.

**Comment by hannesbochmann** [comment]
Should be fixed with the newest releases.
