### ISSUE TITLE
No save-buttons etc. are shown in BE

### ISSUE THREAD

**Issue by twestner** [DMKEBUSINESSGMBH/typo3-mkcontentai#2]
After upgrading from 11.0.2 to 11.0.3 all buttons like save, edit etc. are not shown anymore in the right BE-frame.

See screenshot attached.

Not tested in version 12.

![2023-11-13_21h13_47](https://github.com/DMKEBUSINESSGMBH/typo3-mkcontentai/assets/68050865/821e8920-c5e0-4c97-8a8a-554f659649ac)
![2023-11-13_21h17_03](https://github.com/DMKEBUSINESSGMBH/typo3-mkcontentai/assets/68050865/b52bb7a0-cd3f-4ffb-9200-ffbbfa059bc2)

**Comment by tneugebauer** [comment]
@twestner thanks, we will have a look at this!

**Comment by darthnorman** [comment]
Experienced the same behaviour in T3 v10.4, the newly added ButtonBarHook (Classes/Backend/Hooks/ButtonBarHook.php) seems to be the cause.

**Comment by hannesbochmann** [comment]
Fixed with version 11.0.4/12.0.6
