### ISSUE TITLE
Alt text generation in Filelist (no context menu given)

### ISSUE THREAD

**Issue by bh-teufels** [DMKEBUSINESSGMBH/typo3-mkcontentai#4]
Automatic generation of alternative text working in Content element but i have no context menu to do this in Filelist module.

did i missed something?

my versions:
TYPO3 12.4.11
mkcontentai v12.1.0

**Comment by tneugebauer** [comment]
Thanks again for your input. Functioanlity is availible over the picture icon, but we will improve that as well... 
![context](https://github.com/DMKEBUSINESSGMBH/typo3-mkcontentai/assets/67777751/797cfe05-8d37-4790-ae17-e754ee835541)

**Comment by hannesbochmann** [comment]
This should be fixed by now.
