### ISSUE TITLE
JS-Error after Installation of the extension

### ISSUE THREAD

**Issue by vb-benjamin-eyring** [DMKEBUSINESSGMBH/typo3-mkcontentai#7]
Hi all, 

right after Installation I do get an JS-Error in the backend when accessing the module:

![image](https://github.com/user-attachments/assets/2dfa8f10-6cca-48e7-a1bf-d0716058f079)

Instance Info:
![image](https://github.com/user-attachments/assets/84c1e277-6a87-462c-adc8-38281606dc65)

Running locally on DDEV. 

Can you reproduce that error in your system or is it maybe related to my local setup?

thx
Ben

**Comment by tneugebauer** [comment]
Hi Ben, thanks for getting in touch. We will check your bug report and get back to you asap!

**Comment by hannesbochmann** [comment]
The issue has been fixed and a new version got released. Thanks for reporting.

**Comment by vb-benjamin-eyring** [comment]
Great, thanks for the quick fix! 

Best regards,
Ben
