### ISSUE TITLE
Support for V13

### ISSUE THREAD

**Issue by vb-benjamin-eyring** [DMKEBUSINESSGMBH/typo3-mkcontentai#8]
Hi all, do you plan to provide this extension for V13 as well?

thx,
Benjamin

**Comment by tneugebauer** [comment]
it is: https://github.com/DMKEBUSINESSGMBH/typo3-mkcontentai/tree/13.0

**Comment by vb-benjamin-eyring** [comment]
Thanks for the quick reply!

I was just confused by the missing label in TYPO3 extension rep:

Cheers
Benjamin

![image](https://github.com/user-attachments/assets/d5c49960-6f1a-4cbf-86e3-28b3e5b12bb7)
